### ISSUE TITLE
Distributed FIO:  Kernel cache needs to be dropped on OSD hosts for accurate perf numbers

### ISSUE THREAD

**Issue by shekharberry** [cloud-bulldozer/benchmark-operator#325] opened 2020-04-29 16:48 UTC
Distributed FIO reports abnormally high Read IOPS for random workload. It's reading most of data from Kernel cache with hardly any IO activity on the OSD (disk) in the backend.

I have 3 node Openshift Container Storage cluster with 1 OSD in each node. OSD is hosted on a disk in Azure VM which is capable of delivering 7.5K IOPS. Since we have 3 nodes the max IOPS we can get is 7500 * 3 = 22.5K IOPS from the cluster. But distributed FIO on Ripsaw reports 800K IOPS. This is because FIO is reading from host kernel cache and not from OSDs.

We need to drop kernel cache on OSD hosts between prepare (prefill, write) and read phase to get accurate performance numbers.

**Comment by jtaleric** [comment] 2020-04-29 19:59
@bengland2 @acalhounRH Can you two weigh in? 

My initial take is that this doesn't belong in Ripsaw, as Ripsaw only orchestrates workloads, and shouldn't be aware of the backend storage for example. 

In contrast, Ripsaw doesn't know about Multus, however if you want Ripsaw to use Multus, you can provide the annotations to take advantage of them. 

Thoughts?

**Comment by bengland2** [comment] 2020-04-29 20:30
I agree that ripsaw itself doesn't need to know about cache dropping.    But it should be possible for fio benchmark to know how to do it.    Specifically, it has to do cache dropping on all hosts where the Ceph OSDs run, not the hosts where the pods run (which may be very different).   The ripsaw fio pods are all doing O_DIRECT I/O so they should not be affected by cache dropping anyway.   I think ripsaw fio could start a daemonset on all the hosts that are labeled with cluster.ocs.openshift.io/openshift-storage, which should include all the OSD hosts.  It may include a couple of extra hosts also, but I don't think this is so bad.    The daemonset could do 'echo 3 > /proc/sys/vm/drop_caches' or equivalent (Manoj's Kubuculum does it differently).    We could use cherrypy to have fio call out to this daemonset.    In addition, it will need a toolbox pod to do equivalent of 'ceph tell osd.* cache drop', this drops cache within the OSD processes.

**Comment by jtaleric** [comment] 2020-04-29 22:41
> I agree that ripsaw itself doesn't need to know about cache dropping. But it should be possible for fio benchmark to know how to do it. Specifically, it has to do cache dropping on all hosts where the Ceph OSDs run, not the hosts where the pods run (which may be very different). The ripsaw fio pods are all doing O_DIRECT I/O so they should not be affected by cache dropping anyway. I think ripsaw fio could start a daemonset on all the hosts that are labeled with cluster.ocs.openshift.io/openshift-storage, which should include all the OSD hosts. It may include a couple of extra hosts also, but I don't think this is so bad. The daemonset could do 'echo 3 > /proc/sys/vm/drop_caches' or equivalent (Manoj's Kubuculum does it differently). We could use cherrypy to have fio call out to this daemonset. In addition, it will need a toolbox pod to do equivalent of 'ceph tell osd.* cache drop', this drops cache within the OSD processes.

Might make sense to add it to, https://github.com/cloud-bulldozer/marshall-plan which could deploy the daemonset prior to running ripsaw FIO? Thoughts?

**Comment by manojtpillai** [comment] 2020-04-30 04:29
> I agree that ripsaw itself doesn't need to know about cache dropping. But it should be possible for fio benchmark to know how to do it. Specifically, it has to do cache dropping on all hosts where the Ceph OSDs run, not the hosts where the pods run (which may be very different). The ripsaw fio pods are all doing O_DIRECT I/O so they should not be affected by cache dropping anyway. I think ripsaw fio could start a daemonset on all the hosts that are labeled with cluster.ocs.openshift.io/openshift-storage, which should include all the OSD hosts. It may include a couple of extra hosts also, but I don't think this is so bad. The daemonset could do 'echo 3 > /proc/sys/vm/drop_caches' or equivalent (Manoj's Kubuculum does it differently). We could use cherrypy to have fio call out to this daemonset. In addition, it will need a toolbox pod to do equivalent of 'ceph tell osd.* cache drop', this drops cache within the OSD processes.

I didn't get the distinction, kubuculum does it differently how? kernel caches there are dropped via a daemonset of privileged pods, with a node label specifying where the pods should run:
https://github.com/manojtpillai/kubuculum/blob/7da7c5266637b08a494d8bc116f187215d89ade1/roles/stats_sysstat/tasks/drop_caches.yml#L12

And ceph caches are dopped via the rook-ceph tools pod: https://github.com/manojtpillai/kubuculum/blob/7da7c5266637b08a494d8bc116f187215d89ade1/roles/storage_ceph/tasks/drop_caches.yml#L11

**Comment by bengland2** [comment] 2020-07-13 10:36
am working on a solution to this problem involving privileged pods specifically for cache dropping, invoked by GET on URL.

**Comment by bengland2** [comment] 2020-07-24 18:23
@shekharberry am re-opening, have the following PRs working
https://github.com/bengland2/bohica/tree/kernel-cache-drop
https://github.com/cloud-bulldozer/snafu/pull/196

and this branch works but I have to rebase before making it a PR:
https://github.com/bengland2/ripsaw/tree/fio_drop_kernel_cache

Raul helped me figure out how to pass the pod IPs to fio client pod

**Comment by bengland2** [comment] 2020-07-29 02:22
@shekharberry starting to work.  https://pastebin.com/ydyEf6Je

**Comment by shekharberry** [comment] 2020-07-29 05:29
Thank you Ben for looking into this so proactively. I will give it a try
and let you know if I have any questions.

--Shekhar

**Comment by bengland2** [comment] 2020-07-31 15:09
@shekharberry , [ripsaw PR 378 ](https://github.com/cloud-bulldozer/ripsaw/pull/378) is the PR for fio to drop cache.   It is not merged yet, but I've run it on a very small scale, needs more testing on a larger scale.   This does not drop Ceph OSD cache - although there is some latent support already for that.  Once I get this one done, I'll do similar thing with Ceph cache dropper and then you should be good to go with ripsaw.

**Comment by bengland2** [comment] 2020-09-22 18:44
I did merge, but it failed recently when I tried it on a baremetal cluster with OCP 4.5, not sure what the problem is but it passes CI, the error is that wait_for_daemonset.py is not authorized, might be as simple as: oc create -f resources/kernel-cache-drop-clusterrole.yaml (not in doc yet) .  I'll look into this when time permits.

**Comment by bengland2** [comment] 2020-11-22 16:50
This is fixed, closing it.

**Closed by bengland2** 2020-11-22 16:50 UTC
Labels: not_ready
